chiefwigms/picobrew_pico

app/static/css/main.css

**before**
**after**
Reference for fix: https://github.com/FortAwesome/Font-Awesome/issues/11946

change fontawesome font-family and set an explicit font-weight for supporting custom css

---

app/main/routes_frontend.py
app/main/session_parser.py

Zymatic and ZSeries upon initializing from brew sessions will be identified as `.is_pico` units. This will cause the "first" to be loaded to be used for fetching the picopak recipe.
I believe all UIDs of C/S/Pro units are 32 characters (ie uuids) so should be safe enough to assume that to be true.
I'm uncertain how Zymatic UserSync and ZSeries interact, but will test those flows as well.

fix #Invalid|# error upon recipe importing for pico units (C/S/Pro)

---

app/main/model.py
app/main/routes_frontend.py
app/main/routes_pico_api.py
app/main/routes_picoferm_api.py
app/main/routes_zseries_api.py
app/main/routes_zymatic_api.py
app/main/session_parser.py

`get_archived_sessions_by_machine(uid)` is descending (latest first; oldest last) so flip the logic for querying the archive sessions for a machine to determine last session type and if the machine has had 3 "dirty" (aka beer, coffee, or sous vide) sessions

fix dirty session counter and last session type in zstate response

---

README.md
scripts/pi/firstboot.sh
server.py

In our raspberrypi scripts we need to install nginx due to python only running either in ssl or non-ssl mode. This way the python server is simple (non-ssl) and there is a reverse proxy in front terminating the ssl connection and re-establishing a non-ssl connection to the python server.
This setup requires nginx to run on port 80 and 443 so I'm added command line arguments that can control what interface and port the flask app is running on with details updated in the README.md (all backwards compatible with defaults to `0.0.0.0:80` as previously used).

Nginx with http and https entries to support the different devices types

---

app/__init__.py
app/main/recipe_parser.py
app/main/routes_frontend.py
app/main/routes_pico_api.py
app/main/routes_picoferm_api.py
app/main/routes_zseries_api.py
app/main/routes_zymatic_api.py
app/main/session_parser.py
app/static/js/brew_graph_socketio.js
app/static/js/ferm_graph_socketio.js
scripts/pi/firstboot.sh
server.py

Here are a number of cleanups and fixes with regard to session graphing and socketio usage now that we are acting as a domain on the local network with raspberrypi via nginx.
- clean up and order imports (circular dependency of __init__.py for resolving global `socketio`)
- use relative scheme `//<hostname>` for clientside socketio (https -> https; http -> http) as modern browsers will prevent "downgrading" of the security scheme within a web session
- fix event logic for recovered active session events (recovered sessions weren't storing a top level `session['recovery']` which would produce duplicated event lines in zseries reported session data
- add websocket/ws nginx route
- include `www.picobrew` and `.picobrew` in nginx server_name configuration
Kinda resolves …

Various fixes for socketio and session graphing

---

app/main/routes_picostill_api.py

This fix was staged on a different branch thus never got pushed with https://github.com/chiefwigms/picobrew_pico/pull/49
Resolves the following error in running this code.
```
File ".../picobrew_pico/app/main/routes_picostill_api.py", line 47, in process_picostill_check_firmware
if args.version != latest_firmware['version']:
AttributeError: 'dict' object has no attribute 'version'
```
Working code with couple of requests tested against it.
```
python3 server.py
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
* Serving Flask app "app" (lazy loading)
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
* Running on …
```

fix dict access of args in firmware check

---

app/__init__.py
app/main/config.py
app/main/firmware.py
app/main/routes_pico_api.py
app/main/routes_picoferm_api.py
app/main/routes_picostill_api.py
app/main/routes_zseries_api.py
config.yaml

This has been something I've been working on to allow folks to either force their own firmware, or another version  of firmware that is included in with the server. 
Configuration file would require a new block (see example below or in comments in config.yaml for syntax).
```
firmware: # specify minimum firmware versions to push to your devices (binaries found in ./app/firmware/<device_type>/)
ZSeries: 0.0.119
PicoBrew: 0.1.34
PicoStill: 0.0.35
```
This way users can choose if they want to run unreleased firmware versions without having to modify code to get them. Several of us early beta testers were side loading unreleased firmware or had devices that were in a "beta" release group to get early releases from Picobrew for testing before a full rollout was made available to all Picobrew …

Support Configuration Overridable Minimum Firmware Versions

---

app/main/routes_zseries_api.py

resolves issue reported in https://github.com/chiefwigms/picobrew_pico/issues/57 where the server alias isn't sent to the device for showing locally on the screen of the Z

parrot the server known alias to the ZState request

---

app/main/routes_pico_api.py

Adds API endpoints necessary for enabling the PicoStill to work with a Pico C.
Note that with the 'hasCleanedAck' always returning true, the 'setCleanedAck' endpoint is likely unnecessary, but I've added it for completeness.
Also note that with these additions I was able to successfully use all Pico C functions that I am aware of.

add api support for using pico c with picostill

---

app/main/routes_picostill_api.py

The response for when there is no new firmware available for the devices are the following:
- -1 is expected by PicoStill
- 0 is expected by Picoferm
- F is expected by C/S/Pro
yay for inconsistency.... but at least they are consistent at being massively inconsistent

fix picostill no firmware update response

---

app/main/routes_frontend.py
app/main/session_parser.py

When MacOS shares files to a network drive or removable disk that is formatted differently that doesn't allow some of the metadata fields that MacOS hard drives support you get a bunch of GARBAGE files created in the following filename patterns
- `.DS_STORE`
- `._<filename>.<ext>`
These are storing metadata about the original directory structure and the files themselves... for us the `.DS_STORE` isn't read, but all these hidden file metadata files are. This leads to the following experience for users.

ignore ._ metadata files created by macos -> linux file sharing

---

README.md
app/main/routes_frontend.py
app/main/routes_zseries_api.py
app/templates/navbar.html

The ZSeries has the ability for a user to turn on "session logging" for a connected PicoStill "brewing" session (aka distillation session). All other devices **do not and will not** have this ability to log sessions.
Additionally as the screenshot will allude to the Z devices have experimental firmware involving **automatic boil point detection** where it starts a few specialized steps to determine heat loss to help pin point the boil point of the wash.  This semi-automated distillation feature is not available on any other machine type.
Feature from the Local Server
Similar Feature from Picobrew.com

Picostill Session Support for ZSeries Device Types

---

app/main/routes_zseries_api.py

Fixes the error that occurs on session close when user exits still session, guess yesterday I missed that there was a close session request in the flood of 6 hours of update session logs.
The session logging failures during a PicoStill session will not disrupt the session itself and things continue on the devices as normal operation.
```
Jul 23 15:48:10 picobrew-logger rc.local[8803]: [2020-07-23 15:48:10,340] ERROR in app: Exception on /Vendors/input.csht
Jul 23 15:48:10 picobrew-logger rc.local[8803]: Traceback (most recent call last):
Jul 23 15:48:10 picobrew-logger rc.local[8803]:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447,
Jul 23 15:48:10 picobrew-logger rc.local[8803]:     response = self.full_dispatch_request()
Jul 23 15:48:10 picobrew-logger …
```

fix StillUid -> StillUID for session create and close

---

app/main/routes_zseries_api.py

🤦 should really just switch all `['<field>']` to `.get('<field>')`

Fix z session creation from `KeyError StillUID`

---

.gitignore
app/main/routes_frontend.py
app/static/js/setup.js
app/templates/about.html
app/templates/navbar.html
app/templates/setup.html
scripts/pi/wifi_scan.sh
scripts/pi/wpa_supplicant.conf

About page /about is intended to be a dumping ground of server information eventually encompassing server logs (download link) and various other information to be used by users to report to the maintainers of the server implementation. Some things about the "restart and update" that get a bit wonky
- if there are local conflicting changes the UI doesn't disable the "update and restart" action which will fail to pull new changes due to the conflicts
- if you change the branch that is being tracked isn't master of `chiefwigms/picobrew_pico` the page will technically lie about the latest change (as it is only tracking master branch git sha) and update/restart will update with the custom tracking branch instead
WiFi Setup page has been tested again 2 of my networks on a Raspberry Pi Zero-W …

Create New /about and /setup Experiences

---

app/main/routes_zseries_api.py

Fixes issues raised by https://github.com/chiefwigms/picobrew_pico/issues/85 when using a Z2+ setup. Instead of looking up the device by the sessionId trust the token provided by the device.

trust machine provided `token` for session log updates

---

README.md
app/main/routes_frontend.py
app/static/js/setup.js
app/templates/navbar.html
app/templates/setup.html
scripts/pi/firstboot.sh

Include additional system level setup / configuration options in the `/setup` experience. Here are 2 new settings of the system that are able to be configured:
1) The Access Point Name and Credentials (only supports `wpa_passphrase`)
2) broadcasted hostname which is helpful if you have multiple raspberrypi setup on your network or want something more memorable than `raspberrypi` as the device's hostname.

Custom access point setup

---

app/main/routes_zymatic_api.py

@chiefwigms I don't have a Zymatic to confirm the ordering of the temps reported by the Zymatic... but if `temp1` and `wort` are swapped this was the only place that made sense to me. Everywhere else the temps are referred to by these stored names 🤷‍♂️ 
Reference in Issue #111 and Facebook posts by Matt Johnson, https://www.facebook.com/groups/Picobrewers/permalink/2734260643519579/

Temp sensors misidentified for Zymatic graph #111

---

app/static/css/main.css
app/static/js/convert_units.js
app/static/js/pico_recipe.js
app/static/js/zseries_recipe.js
app/static/js/zymatic_recipe.js
app/templates/new_pico_recipe.html
app/templates/new_zseries_recipe.html
app/templates/new_zymatic_recipe.html
app/templates/pico_recipes.html
app/templates/units_selector.html
app/templates/zseries_recipes.html
app/templates/zymatic_recipes.html

There is one edge case that isn't working right now. I didn't dive into Tabulator too much... but the accordion logic is messing with my convert temp logic. Tried various different callbacks from Tabulator for formatting data and none of them worked (or I just plain screwed up). Though this does work fairly well and if you happen to do the following hairbrained actions (yeah I know who you are!) then well just change your behavior #user-error.
Displaying demo of feature at work (browse/edit recipe)
Displaying demo of feature at work (create/new recipe)
**Not handled/covered by this PR.**
1) expand a recipe
2) collapse same recipe
3) convert units
4) expand same recipe
5) yeah... just refresh the page... as this doesn't work right now
Demo of the edge case issue.
Resolves #66 for giving …

Frontend Support for Changing Temperature/Units

---

app/static/js/pico_recipe.js
app/static/js/zseries_recipe.js
app/static/js/zymatic_recipe.js

```
zseries_recipe.js:110 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
at Object.mutator (zseries_recipe.js:110)
```
This error is caused due to a new step being added not having anything set for the data so `data.location` returns undefined which when used without a null-safety check throws an error and fails to create the new row for the recipe.

Issue #145 fix new recipe step (data.location isn't set so throws error)

---

app/main/routes_frontend.py
app/static/js/pico_recipe.js
app/static/js/zseries_recipe.js
app/static/js/zymatic_recipe.js

Fixed the recipe add step buttons by copying the row and changing the name to "New Step."
For the Pico S/C/Pro recipes, improved the locking of the first three rows, but other rows can still be moved into the first three since Tabulator doesn't appear to support making some rows immovable.
Sort recipes by recipe name and sessions by filename in reverse order which puts the newest at the top.

Fix add step button, sort lists

---

app/static/js/pico_recipe.js
app/static/js/zseries_recipe.js
app/static/js/zymatic_recipe.js

As found in https://github.com/chiefwigms/picobrew_pico/pull/146 the hop_time calculation wasn't retriggered upon `location` changing for the row so I added this `cellEdited` callback to the `location` cells as well.

calculate hop_time again upon location changes

---

app/__init__.py
app/main/config.py
app/main/firmware.py
app/main/model.py
app/main/recipe_import.py
app/main/recipe_parser.py
app/main/routes_frontend.py
app/main/routes_pico_api.py
app/main/routes_picoferm_api.py
app/main/routes_picostill_api.py
app/main/session_parser.py
app/main/test_recipe_import.py
app/main/test_routes_frontend.py

- resume picoferm active session upon restart
- fix z recipe unique id (after importing you could in theory have multiple of the same `id`)
- various flake8 warnings (line size, unused imports, multiple lines, spaces on lines, etc)
- on initialization sessions would be eagerly created and replaced

restore active picoferm session upon reboot

---

app/main/routes_frontend.py
app/main/session_parser.py
app/static/js/brew_history.js
app/static/js/ferm_history.js
app/static/js/iSpindel_history.js
app/static/js/server_management.js
app/templates/brew_history.html
app/templates/ferm_history.html
app/templates/iSpindel_history.html

**Features Included**
Backport invalid files and recover/restore session for **iSpindel** session types.
Add download and delete buttons to all session entries across the 3 different session types (`brew`, `ferm`, `iSpindel`)

include ability to download and delete all types of session files

---

app/templates/recipe_list.html

Tabultaor 4.8 deprecation notices made mention of `dataEdited` being renamed to `dataChanged`, but instead we should have been listening to these following events instead (as we programmatically calculate some of the data): `rowAdded`, `rowDeleted`, `rowMoved` (were already listening to that callback), and `cellEdited`.

refactor and fix usage of deprecated tabulator method

---

app/main/session_parser.py

enough of seeing reports of invalid active sessions killing things and only fixing a single type... all json file handling of incomplete files (at least well known incomplete files) should be handled similarly...
refactored and combined the 3 different approaches in code into a single 1 before adding yet a 4th one for PicoStill sessions 😠

centralize recovery from invalid session files ('', '[', '[{},{},', etc)

---

app/main/routes_iSpindel_api.py
app/main/routes_pico_api.py
app/main/routes_picoferm_api.py
app/main/routes_picostill_api.py
app/main/routes_zseries_api.py
app/main/routes_zymatic_api.py

There are a few experiences that require "registering" the device (meaning there is an entry in the `active_*_sessions` variables). The only ways to eagerly create an entry here is:
1) by adding an alias in the config.yaml file
or
2) running a session (drain, rinse, clean, brew, etc)
Instead of relying on a session being run or configuration file being updated (either via the UI or file share) let's just eagerly create the session entry upon first request from the devices... this way they show up on index page immediately upon turning them on (upon a window refresh.. with the lack of a socketio publish for "new machine detected"). 
This unlocks those few experiences that require an actual active session or a machine "alias". Including the "waiting to brew" title on the index card as well …

eagerly create in memory session (not file bound)

---

app/main/model.py
app/main/routes_frontend.py
app/main/routes_picoferm_api.py
app/main/session_parser.py
app/static/css/main.css
app/static/js/index.js
app/templates/index.html

This changes the functionality of the PicoFerm device. Currently a session will be created when the device turns on and sends data to the server for the first time. Instead the server will "register" an empty session (in-memory) and only when the user marks "Start Fermentation" will data flow from the device to the server.
This is accomplished by switching between `10,0` (fermentation in progress) and `2,4` (do nothing) as the response codes to the device.
I'm not sure what the intention of having a `2,16` (complete/stop sending data) to the PicoFerm actually does differently from just flipping to `2,4` as I have implemented here which is what we are sending at the 14d mark (should we remove that? display a count down in some other way? likely to do that later as a different PR …

Issue #134 add start and stop fermentation buttons for picoferm device

---

app/main/routes_frontend.py

With the introduction of the eagerly created sessions this wasn't playing nicely with this conditional that wouldn't allow an alias created (not updated) for an existing device... this fixes that, though would still be a better overall user experience if the UID was an optional dropdown allowing any "detected" device to be more easily aliased. Maybe something to work on later.

Issue #175 allow an active device (one with a session entry) to be aliased

---

app/main/routes_frontend.py
app/templates/about.html
app/templates/navbar.html
scripts/pi/00-run-chroot.sh
scripts/pi/wifi_scan.sh

In preparation for a beta6 release (with complete working offline wireless configuration) I also decided to add in a new concept to our releases known as "release variants". For not we have 2 (future we may have more 🤷‍♂️): latest (contains the latest of raspbian and all related firmware) and stable (contains a reverted rpt4 release of the WiFi firmware that supposedly adds stability???).
Other features included of importance:
- a standard `platform` (memorized at start up) template variable sent to conditionalize what shows up in the "system" navigation dropdown (hiding RaspberryPi only supported actions from non RaspberryPi deployments) as well as a new `render_templates_with_defaults` helper function... we need to make sure to always use this function moving forward
- image creation …

Setup Multi-Variant Image Builds and Various Other Improvements

---

app/__init__.py
app/main/model.py
app/main/session_parser.py

In theory the problem is a single line (the one in __init__.py), but in the case of refactoring I also reorganized the session_parser.py code to allow for before or after loading of the initial server data context.

persist machine_type when recovering session

---

app/main/session_parser.py

Simply when restoring picoferm sessions the `session.uninit` wasn't being set so set this explicitly to `False`. Upon doing so it was immediately found that using the string stored as `session.start_time` would fail when being used for date math (to determine automatic end of session.. which maybe we remove anyways?) so converted that to a date object as well.

Issue 167 - mark session initialized for PicoFerm upon server boot

---

app/main/routes_pico_api.py
app/main/routes_zseries_api.py
app/main/routes_zymatic_api.py
app/main/session_parser.py

This will prevent the issue that caused Issue #209 to occur, however won't fix any of these such session files that exist... users would need to manually change the recipe name's "#" in the session file to "%23" (the url encoding of "#").

encode specific recipe name characters (' ' and '#')

---

app/main/session_parser.py

Regardless of fixing the way these files can get corrupted like this. Simply a brew session that misses a "complete" or otherwise isn't marked correctly as finished (existing or otherwise) we should look at recovering as many as we can (short of a power outage in the middle of writing a line in the file).
A long term fix for "invalid written JSON structure" can be found in https://github.com/chiefwigms/picobrew_pico/issues/216 and I'll defer fixing the "problem" until then. I've run this locally where on my system I have 6 different types of invalid sessions across the different types of devices and this fixes nearly all of them (short of the session files that have invalid names ie '#' in the filename, wrong date string, non integer, etc).
**current behavior with the new try/except …

attempt to recover from various invalid session forms... #209

---

app/main/routes_devices.py

existing behavior:
fixed behavior:

fix exponential notation device uid forcing to parse form input as strings on the python side

---

app/main/routes_zseries_api.py

related to the KeyError found in https://github.com/chiefwigms/picobrew_pico/issues/229

z state does not always contain a boilertype apparently

---

app/main/routes_iSpindel_api.py
app/main/routes_picoferm_api.py
app/main/routes_zseries_api.py
app/main/units.py
app/static/js/convert_units.js

@BuckoWA take a look at the changes I made to iSpindel. Specifically related to when `create_new_session` is called, since that creates a file. Prior to this change if you setup an iSpindle a file is created with '[' and then if you power cycle the server fermentation is marked as active due to there being a file. This is now aligned with the picoferm where you have to click `START` in order to get a file created and start monitoring fermentation progress. I also ended with an exception the first time logging from the iSpindel (using Postman) exception follows, but in changing around that conditional I've resolved that problem.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request() …
```

update iSpindel routes to support iSpindle, and other temperature related stuff

---

app/static/js/convert_units.js

addresses the header text bug reported in https://github.com/chiefwigms/picobrew_pico/issues/231 when switching temperature units

fix temperature header changes in recipe list

---

app/main/recipe_parser.py
app/main/routes_frontend.py
app/main/session_parser.py
app/static/css/main.css
app/static/js/brew_graph.js
app/static/js/brew_graph_socketio.js
app/static/js/pico_recipe.js
app/static/js/server_management.js
app/static/js/zseries_recipe.js
app/static/js/zymatic_recipe.js
app/templates/brew_history.html
app/templates/pico_recipes.html
app/templates/recipe_actions.html
app/templates/zseries_recipes.html
app/templates/zymatic_recipes.html

Few things changed in this PR:
First and foremost is a new "create" and "upload" recipe button on the recipe library experience:
Secondly is a change to the session view to extract metadata from the session into the experience:
For the date parsing I switched around to parse the data at the same time we parse the session file and pull parsed date along vs parsing it later.
Thirdly I've been hearing that folks have copied pico files into zymatic and zseries and being confused why they don't work. So added a sanity check that the locations of a particular recipe match to the known locations supported/expected by the machine type. Raising exceptions to report the recipe as "invalid" in the UI when this happens. Likely with the first change above "upload" this will likely become more …

upload and new recipe actions, session history changes and shared graphing tooltip

---

app/main/routes_server.py
app/templates/setup.html

Better to have 
than an internal server error.

conditionalize the server scripts in /setup experience for non raspberrypi setups

---

app/main/routes_pico_api.py

Pico C/S/Pro units that didn't have an alias entry in the config would end with a bootloop.
```
Feb 06 09:00:39 raspberrypi rc.local[268]: 127.0.0.1 - - [06/Feb/2021 09:00:39] "GET /API/pico/getFirmware?uid=<uid> HTTP/1.0" 500 -
Feb 06 09:05:58 raspberrypi rc.local[268]: 127.0.0.1 - - [06/Feb/2021 09:05:58] "GET /API/pico/register?uid=<uid> HTTP/1.0" 200 -
Feb 06 09:05:58 raspberrypi rc.local[268]: 127.0.0.1 - - [06/Feb/2021 09:05:58] "GET /API/pico/picoChangeState?picoUID=<uid>&state=2 HTTP/1.0" 200 -
Feb 06 09:06:00 raspberrypi rc.local[268]: [2021-02-06 09:06:00,106] ERROR in app: Exception on /API/pico/checkFirmware [GET]
Feb 06 09:06:00 raspberrypi rc.local[268]: Traceback (most recent call last):
Feb 06 09:06:00 raspberrypi rc.local[268]:   File …
```

proper handling of an unknown machine_type for pico firmware

---

app/main/routes_frontend.py
app/main/routes_pico_api.py

The file glob match used to detect sessions of a machine was not matching filenames appropriately anymore.
Ported similar "num_sessions_since_clean" from z into the pico series devices (using comment to decide response format... I don't have a working pico device so can't test).
Tested both z and pico via manually adding files locally and curling the API.
```
curl "localhost/API/pico/getActionsNeeded?uid=pico-needs-cleaning"
#7#%
```
```
curl --location --request PUT 'localhost/Vendors/input.cshtml?type=ZState&token=z-needs-cleaning' \
--header 'Content-Type: application/json' \
--data-raw '{
"BoilerType": 1,
"CurrentFirmware": "0.0.119"
}'
{
"Alias": "ZSeries",
"BoilerType": 1,
"IsRegistered": true,
"IsUpdated": true,
"ProgramUri": null,
"RegistrationToken": -1,
"SessionStats": { …
```

fix z series clean logic (file glob match) add add/port logic for pico series device

---

.gitignore
app/main/routes_frontend.py
app/templates/index.html

and some refactoring to lessen duplicate markup and improve readability.
Before the devices were all expanded when you load the page, which makes you scroll to get to the info you want - like if you are fermenting, and not brewing.
This merge request collapses inactive devices so the active ones are more prominent.

Collapse inactive devices by default

---

app/main/routes_devices.py
app/templates/devices.html

After adding and then deleting devices, the yaml generated leaves an empty dict and the "No devices configured" message no longer displays.

Display no devices configured

---

app/main/session_parser.py
app/templates/brew_history.html
app/templates/ferm_history.html
app/templates/iSpindel_history.html
requirements.txt

- calculate from data log the end date of sessions
- port machine/device, start date, end date view for ferm and ispindel devices
- fix timezone for start date and end date to be server timezone using dateutils helpers
Brew Session
Ferm Session
iSpindel Session

Include Calculated End Date in History

---

scripts/pi/00-run-chroot.sh
scripts/pi/picobrew.com.conf

1) ignore client timeouts (seems that picobrew firmware doesn't wait for a response and is a fire and forget for data logs)
2) disable all error and access logging for /socket.io requests... these are annoying me so much
3) symlink the nginx config for picobrew_pico from the application installation folder (`/picobrew_pico/scripts/pi`) instead so `git pull` can update the nginx configuration (this paired with @cgalpin's ideas around running a script post git pull, https://github.com/chiefwigms/picobrew_pico/pull/266, can restart nginx if needed based on file modification date)

[nginx config] ignore client timeouts, disable socket.io access logs and setup nginx config for easy updating

---

app/main/routes_server.py
scripts/pi/00-run-chroot.sh
scripts/pi/post-git-update.sh

Take 2
This will cover the current need to update existing installations with bluetooth disabled, and a place to add additional checks in the future.
It will run on reboot if/when update_boot is true, as well as when the server is updated via the UI when on a raspberry pi.

Added hook/script to run after git updates

---

app/main/tilt.py

These special characters ':' in the href / id fields in HTML break the expand functionality of the accordians in bootstrap. So I've decided to remove both the ':' (linux/win address) and '-' (macos address). These also just caused the device name to be longer which just looked weird in narrow displays (phones).
cc/ @cgalpin have a look, though fairly simple

remove special characters in the tilt address break due to html anchor incompatibility

---

app/main/session_parser.py

to properly auto start a poll for picostill data we need to know the ip address... unfortunately the setup right now doesn't have a way to distribute that across a raspberrypi restart and likely the dhcp lease might change anyways since the dhcp server could also have restarted.
for now I'm just removing this

remove auto start poll for picostill (ip address isn't known)

---

app/static/js/base_recipe.js

@LEFsher I'm not sure how you are getting a row that is invalid as this code for the tooltip doesn't validate the row entry that happens else where and at least on my dev machine is working as expected in both F and C modes.

correct the valid Celsius range for tooltip

---

Dockerfile
app/__init__.py

this catches any import failure (file/command `bluetoothctl` not found)

wrap tilt imports (which include bluetooth) in a try/except

---

app/main/routes_pico_api.py
requirements.txt

Fixed the identification of Deep Clean sessions for the Pico S/C/Pro. The session name is in mixed case from the name of the session json file, and is being compared to upper case session names. This results in a Deep Clean message whenever there are 3 or more sessions for the device, regardless of what they are. Making the comparison case insensitive fixes this.
Added [eventlet](https://eventlet.net) to the Python requirements.txt file in order to remove the warning message when starting the server. It appears to have no other effect on the operation of the server.

Fixed a couple of minor bugs

---

scripts/pi/picobrew.com.conf

for some reason proxy headers and client timeout configuration was only added to https and not into http as well... fixing that with this change

port proxy headers and config into http (c/s/pro/ferm/still)

---

app/main/model.py
app/main/routes_devices.py
app/main/routes_frontend.py
app/main/still_polling.py
app/templates/devices.html
app/templates/index.html
scripts/docker/nginx/conf/picobrew.com.conf
scripts/pi/00-run-chroot.sh

Having a manual way to add the ip_address actually makes it easier to setup for testing things. While this gives a way to fix things if say your pi or server turns off during a session (i did this while testing the integration).
--
random other change: 00-run-chroot.sh is a reference to a step that no longer exists and I also decided it was time to just name the local domain picobrew.local 😜

setup initial embedded-ui, provide static way to add picostill.ip_address and better logging format and details

---

app/main/routes_zseries_api.py

For a Zseries session the start time of the session would mismatch what was shown in the graph.
When the session was completed and reviewed in the history or if the session was recovered the start time would match the graph.  This mismatch only occurs during the initial session creation.
To resolve this issue I changed from using UTC time to Local Time of the active session creation time.  UTC time is using in other locations in this file.  As I am not sure the overall intent of those other locations I did not change them.  As the start time would recover in the local time I believe the intent is that the session should be created in local time.
With this change a Zseries session start time will match the graph and how it is displayed from a recovered session.

Zseries Session Start Time Mismatch

---

app/main/session_parser.py

I found that after a power outage an active Tilt session would not load.  When the server was rebooted the session would show as active but no data was on the graph.
I found that this was due to NULL characters being at the end of the log file.
Since there was already a recover_incomplete_session function, to resolve this issue I added an endswith for NULL (\x00) which reverse strips them and fixes an open comma which recovers the session properly.
With this update a corrupted file is automatically recovered properly.
Here is a example of a corrupted session file.  It has been renamed from .json to .txt so I could upload it.
[20210807_164541#Orange-C71885D66A9C.txt](https://github.com/chiefwigms/picobrew_pico/files/7047325/20210807_164541.Orange-C71885D66A9C.txt)

Tilt Session Recovery from Power Loss Corruption

---

app/main/session_parser.py
app/templates/index.html
requirements.txt

To get more utility (pun intended) out of the last session "type" and "name" decided to go and collapse a bunch into "UTILITY" and also mark "Deep Clean" as the same a "Clean" cause after all it is a clean session type.
Before:
After (showing the color status meaning):
Fixed a bug I introduced in invalid_sessions not being defined at the global state... 🐞

Combine a few sessions into UTILITY and fix DEEP CLEAN

---

app/main/routes_tilt_api.py
app/main/tilt.py
scripts/python/scan_tilt.py

The tilt pro has 1 more decimal place for both temp and gravity readings that weren't measuring right on pytilt (the python script we started from) nor in our application. This fixes that by dividing both (non decimals) by an additional 10.

fix tilt pro resolution issue

---

app/main/routes_zseries_api.py
app/main/session_parser.py
app/static/js/brew_graph.js
app/static/js/brew_graph_socketio.js

- include additional data submitted from ZSeries devices into the brew session file
- visually display pause/error state as plotBand
- refactor chart styling in javascript vs in python code (need to port to pico and ferm devices)
- include plotBand label.text into the chart tooltip.formatter
I've tested this with manually created files generated from a prior brew session, I don't know how to trigger all the different error conditions on the device but I'm certain that the device only sends `int` types for `PauseReason` and `ErrorCode` so tracking those as `int` for now. While only "translating" the ones that we know about as we detect them... Right now the main one is `PauseReason: 1` which is when you program a pause (or the recipe ends). I'm not positive that the error codes listed on …

Update Brew Session Graphing (error/pause states)

---

.gitignore
app/main/config.py
app/main/routes_server.py

Haven't exposed to the UI, but for now folks that want to backup their recipe and session files without using samba... can do so from `http://<ip-hostname>/backup/recipes` and `http://<ip-hostname>/backup/sessions` which will appropriately zip up the existing `app/recipes` and `app/sessions` folders respectfully and provide the resulting file as a download.
I've also found that `send_file()` has arguments to setup no-cache headers and the correct "download as file" headers so no need to create a manual response structure with headers instead leveraging the optional arguments of `send_file()`.

Issue #138 - include a backup recipe and session file capability

---

.gitignore
app/main/routes_devices.py
app/main/routes_pico_api.py

There was a thread between Diane, Kevin and myself on Facebook that a factory reset C was failing to load firmware.
In this situation here are the only requests made to the server from the device:
```
192.168.72.183 - - [25/Jan/2021:14:43:31 -0500] "GET /API/pico/error?uid=<uid>&code=17 HTTP/1.0" 499 0 "-" "-"
192.168.72.183 - - [25/Jan/2021:14:43:53 -0500] "GET /API/pico/register?uid=<uid> HTTP/1.0" 200 5 "-" "-"
192.168.72.183 - - [25/Jan/2021:14:44:00 -0500] "GET /API/pico/getFirmware?uid=<uid> HTTP/1.0" 500 290 "-" "-"
```
without the proceeding request to `GET /API/pico/checkFirmware?uid=<uid>` which has been seen before in practice. This is likely due to the firmware being factory reset to knowing somehow that the firmware already needs to be updated? Only happens when the …

Random fixes - New Device Firmware Failing to Loading

---

app/main/model.py
app/main/routes_zseries_api.py

This technically could still get into the **Error 5: TOO COLD** state by having the Z report the wrong boiler type for the first ZState request sent to the server. Without mucking with config and other stuff users would have to actually know their boiler type... so figured this was good enough to get that more helpful error than to cause more confusion about "my Z says too cold... what do I do now?" type inquiries.

Include a ZBackendError for BoilerType Mismatch

---

app/__init__.py

I ran into an issue in my environment where I hadn’t pre-populated the folders within the mounted volumes and things *mostly* worked correctly until I couldn’t start a brew session.  Adding the recipes/pico/archive folder manually fixed the issue, so adding those to the init set of folders to create.

adding missing folders to init

---

app/main/routes_devices.py
app/static/js/base_recipe.js
app/static/js/pico_recipe.js
app/static/js/zseries_recipe.js
app/static/js/zymatic_recipe.js
app/templates/recipe_list.html

fix deprecated tabulator use of tooltips and include centralized edit/save detection logic (opposed to <script> tags everywhere) and raise alert flag when duplicated recipe.id are found
example alert flag for duplicated recipe.id found

Deprecated Tabulator Fix and Improve Error Handling
