- README.md
- app/__init__.py
- app/main/__init__.py
- app/main/recipe_parser.py
- app/main/routes_frontend.py
- app/main/routes_zseries_api.py
- app/static/js/new_zseries_recipe.js
- app/templates/navbar.html
- app/templates/new_zseries_recipe.html
- app/templates/zseries_recipes.html
- config.yaml
This is the implementation I have built for Z most of which looks similar to the existing Zy except for the translation to the API layer... in theory we should share some of the underlying code in a later refactor by going Model-View-Controller and having all devices share a similar underlying `Model` (Underlying data structures) and having specific device purposed `View` (API presentation) and `Controller` (API implementation translating Model -> View for the machines).
missing behavior(s): group brewing*, pico pak, picostill*, error codes exposed to session graphs
_*I'm in the process of trying to acquire another Z machine and already have a PicoStill in my possession for this exact purpose of supporting group brewing (more than one Z brewing the same beer at the same time) and the …
> Initial ZSeries API Implementation

- app/main/routes_zseries_api.py
- :fire: apparently sessionId != 0 firmware barfs (hard failure of initial session logging for the Z firmware)
- 🐛 removed old naming from guid -> session to stay consistent everywhere
> fix some issues with initial server startup

- Dockerfile
- README.md
- app/__init__.py
- app/main/config.py
- app/main/model.py
- app/main/recipe_parser.py
- app/main/routes_frontend.py
- app/main/routes_zseries_api.py
- app/main/session_parser.py
- docker-compose.yml
In testing Z functionality today with the device I had to edit some code and decided to do that during a running brew session. In doing so I decided to go down the route of fixing it so upon running the server again the data is logged successfully against the prior active brew session.
> Fix active session after crash

- app/__init__.py
- scripts/pi/firstboot.sh
also fixs a small typo in `localhost` in the nginx configuration
> Apply CORs configuration to socketio

- app/main/routes_zseries_api.py
- app/static/js/brew_graph.js
- app/static/js/brew_graph_socketio.js
- convert celcius -> fahrenheit for ZSeries temps in session data
- add a 6th theme color (palette and example graph below)
> Zseries fix brew graph units

- .gitignore
- app/__init__.py
- terraform/README.md
- terraform/get_public_ip.sh
- terraform/main.tf
- terraform/variables.tf
Added Terraform to provision the picobrew server in AWS. I also had to update the app itself to create the recipes and sessions directories, if they don't already exist, as that was the cleanest way to initialize the AWS file system used by the server to persist the data.
> AWS terraform

- .github/workflows/python-app.yml
- app/main/test_routes_frontend.py
- test_server.py
Adding a simple workflow for Github Actions to verify application startup, basic set of test functionality, and barebones code styling/linter before accepting a push or pull request as valid.
To view how this will work in the future (still changing slightly, but wanted to open visibility and conversation around it) -> https://github.com/tmack8001/picobrew_pico/pull/1
Later on I want to:
- automatically build & push of the docker image
- deploy to the example AWS EC2 node
- upon a specific tag present making a draft github release
- increase test coverage and potentially have a full brewing or fermenting session on each device type verified
> tests and update github action

- app/main/routes_frontend.py
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/pico_recipes.html
- app/templates/zseries_recipes.html
- app/templates/zymatic_recipes.html
Here is a preview of what this UI looks like for the ZSeries (copy/pasted for the other devices as well)
Upon loading the recipes I've also logged the warnings about the issues with the recipes.
> Include safe error handling and persistence of invalid recipe files

- app/main/routes_frontend.py
- app/static/js/brew_history.js
- app/static/js/ferm_history.js
- app/static/js/pico_recipe.js
- app/static/js/server_management.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/brew_history.html
- app/templates/ferm_history.html
- app/templates/invalid_file.html
- app/templates/pico_recipes.html
- app/templates/zseries_recipes.html
- app/templates/zymatic_recipes.html
There was a long thread today on FB about the /brew_history page ending with a barfed `Internal Error Occurred` page... we shouldn't trust any user input (including the files that the server builds).
> Port Invalid File logic for Sessions (Brew and Ferm)

- .dockerignore
- Dockerfile
- README.md
- app/main/routes_frontend.py
- docker-compose.yml
As talked about in https://github.com/chiefwigms/picobrew_pico/issues/91 the current docker image recommends mounting the source directory which bypasses the .dockerignore file and includes the user's `.git` folder into this setup. This could be nice if paired with ssh keys for developers/contributors, but I'd discourage running this way and instead setup to use `docker-compose up --build` instead to copy in your source files (without .git and other ignored system level files) into the build Docker image.
In this change I'm also setting up a manually linked git repository to our remote git source known as `origin` this is so that there is an initialized and populated `.git` folder within the Docker image that can be used with git commands to communicate with github to find what is the …
> setup git remote for docker containers

- app/main/session_parser.py
Appears to fix issue #116. 
Change the order of the list of dict's to match PR #114
> Swap order of dict list for zymatic graphing updates.

- app/static/css/main.css
- app/templates/navbar.html
Edited the nav bar on mobile so it collapses into a dropdown as opposed to taking up half the screen.
> Collapsed nav on mobile

- .gitignore
- app/__init__.py
- app/main/__init__.py
- app/main/config.py
- app/main/model.py
- app/main/routes_frontend.py
- app/main/routes_iSpindel_api.py
- app/main/session_parser.py
- app/static/js/iSpindel_graph.js
- app/static/js/iSpindel_graph_socketio.js
- app/templates/iSpindel_history.html
- app/templates/index.html
- app/templates/navbar.html
- config.example.yaml
Additions add graphing support for iSpindel use. Also adds active and archive folders for iSpindel sessions. iSpindel configuration requires Server Port to be picobrew.com and the Path / URI to be /API/iSpindel
> Adds iSpindel support to the server

- app/static/css/main.css
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/new_pico_recipe.html
- app/templates/new_zseries_recipe.html
- app/templates/new_zymatic_recipe.html
- app/templates/pico_recipes.html
- app/templates/setup.html
- app/templates/zseries_recipes.html
- app/templates/zymatic_recipes.html
Things that are working:
- view recipe (total and cumulative boil times are calculated)
- edit `step_time` or `drain_time` cells (total and cumulative boil times are recalculated before saving)
**Things not working yet:**
- new recipes (need to port all of this 3 more times into the new recipe experience 😆 )
c/s/pro recipes
Zymatic recipes
ZSeries recipes
Resolves https://github.com/chiefwigms/picobrew_pico/issues/136
> calculate total run time, individual step times (step+drain), and cumulative hop 'boil' times

- app/static/css/main.css
- app/static/js/convert_units.js
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/new_pico_recipe.html
- app/templates/new_zseries_recipe.html
- app/templates/new_zymatic_recipe.html
- fix js errors for unit conversion on new recipe (upon attempting to double convert)
- add hop_time calculation for new recipes initial load (table loaded, but no tables reference)
- consistent save behavior between update and create experiences (icon and save at top)
> Some Client Error Fixes and Consistency Stuff

- app/main/routes_frontend.py
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/pico_recipes.html
- app/templates/recipe_list.html
- app/templates/zseries_recipes.html
- app/templates/zymatic_recipes.html
I decided as part of this... since I didn't like copy/pasting a bunch of stuff around yet again to add a feature to the recipe list (which is other than ABV and IBU on Pico C/S/Pro machines the exact same code) to refactor everything into recipe_list.html.
This makes it easier to share "recipe instructions" with other people without having to deal with Samba, ssh, etc... which are complex tools used by wizards 🧙.
> Download Recipe Button

- app/main/routes_frontend.py
- app/static/css/main.css
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/base.html
- app/templates/import_pico_recipe.html
- app/templates/import_zymatic_recipe.html
- app/templates/new_pico_recipe.html
- app/templates/new_zseries_recipe.html
- app/templates/new_zymatic_recipe.html
- app/templates/recipe_list.html
- app/templates/setup.html
Only thing missing right now is the ability to rename the recipe in the UI. I'll look to add that for any recipe tomorrow morning if I get a chance.
**zymatic**
**zseries**
**pico**
> Issue #123 Add Ability to Copy Recipes

- app/__init__.py
- app/main/routes_frontend.py
- app/static/js/devices.js
- app/templates/base.html
- app/templates/brew_history.html
- app/templates/devices.html
- app/templates/ferm_history.html
- app/templates/iSpindel_history.html
- app/templates/import_brewhouse_recipe.html
- app/templates/index.html
- app/templates/navbar.html
- app/templates/new_pico_recipe.html
- app/templates/new_zseries_recipe.html
- app/templates/new_zymatic_recipe.html
- app/templates/pico_recipes.html
- app/templates/setup.html
- app/templates/zseries_recipes.html
- app/templates/zymatic_recipes.html
- config.example.yaml
- requirements.txt
To go with the fully hands off "raspberrypi" setup theme I've added a "device registration" experience.
Since some users have a hard time editing files and depending on the editor will corrupt the file with "smart quotes" (yeah M$ Word looking at you!! 🤬🤮). This combined with the WiFi experience will make for a great no touch experience... just flash the image and set everything up in the web UI.
**I've still need to finish up the "delete" and "update" experiences here,**  but wanted to get some early eyes on the direction and approach to this problem.
> UI device registation

- app/main/routes_frontend.py
@chiefwigms and @PhracturedBlue I need to still test to make sure this works with both pre-beta5 and beta5 releases... will try to do that tonight if I can find the time to do it.
> forward and backwards compatible wifi settings fix

- app/main/recipe_parser.py
- app/main/routes_frontend.py
- app/static/js/pico_image.js
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/new_pico_recipe.html
- app/templates/recipe_list.html
In the GIF I noticed that the edit experience of newly created recipes was missing the default image (if you didn't upload one...) I have since fixed that just decided not to do another screen recording.
> provide edit recipe experience (name, notes, image, abv, ibu if supported)

- app/main/routes_server.py
> List IP Addresses - support debian `hostname -I` (list all ip addresses)

- app/main/routes_frontend.py
- app/main/session_parser.py
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/base.html
- app/templates/recipe_list.html
https://github.com/chiefwigms/picobrew_pico/issues/212 found that recipes with "'" which are common when referring to generic styles with someone's possessive noun in front... "Annie's Ale", "Distiller's Blank Slate", etc.
Also threw in some local debugging I added for some of the invalid session investigations from earlier with folks.
> escape user provided recipe name as ' and " will breakout of our HTML

- app/main/routes_picoferm_api.py
we should later add a count down/up timer into the UI, but for now let's just remove the automatic closure of fermentation
> remove picoferm 14d fermentation complete timer transitioning to user controlled

- app/static/css/main.css
- app/templates/recipe_list.html
> treat recipe.notes as markdown and render as converted html

- app/main/routes_devices.py
Without this check, empty values can be written to config.yaml that cannot be deleted. They also look odd without a name :)
> Make device alias and uid required when add devices

- app/main/routes_iSpindel_api.py
resolves https://github.com/chiefwigms/picobrew_pico/issues/247
ref: https://webargs.readthedocs.io/en/latest/advanced.html#setting-unknown
> support unknown fields in the request body for ispindel

- app/static/js/base_recipe.js
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/new_pico_recipe.html
- app/templates/new_zseries_recipe.html
- app/templates/new_zymatic_recipe.html
- app/templates/pico_recipes.html
- app/templates/zseries_recipes.html
- app/templates/zymatic_recipes.html
Added some more language in the tooltips as well as fixed the temp range for when a user switches to Celsius (and for pico 0-100 was just celsius, but UI was Fahrenheit 🤷‍♂️).
Later was thinking of adding a .md file into the support section describing the table and recipe structure a bit more with examples of setting up a `recipe.notes` section for ingredients like the one I shared that is formatted.
> bit more details to the tooltips of the recipe table and fix the celcius help range text

- app/main/tilt.py
Moving the `while True` loop within the async function method for scanning for tilt devices prevents an onslaught of run away threads all fighting over system resources and ultimately the bluetooth device (only one thread can scan anyways).
cc/ @cgalpin and @Intecpsp who have also been helping identify that this was related to the Tilt polling. Though my raspberrypi never fell over or become unresponsive others have reported this in https://github.com/chiefwigms/picobrew_pico/issues/274 and in PMs.
> move infinite loop within the spawned async thread vs outside

- scripts/pi/post-git-update.sh
Leveraging the post git upgrade script and the new source controlled ngnix configuration we can more easily modify nginx configurations on server update.
I want to test this script on a raspberrypi to verify syntax and such works thus leaving as a draft to prevent merging.
> Issue 199 - allow for automatic reconfiguration of nginx configuration

- app/main/routes_frontend.py
- app/main/routes_pico_api.py
- app/main/routes_zseries_api.py
~98% performance reduction on my MacBook Pro (visible by a hand full of requests)... can only imagine this will also improve the performance on a RaspberryPi+SD Card drastically
**before (with 100s of sessions on MacBook Pro)**
**after (with 100s of sessions on MacBook Pro)**
> Issue 255 - speed up the clean detection (no need to parse any brew session files, just the names)

- app/static/css/main.css
- app/static/img/iSpindel.svg
Closes https://github.com/chiefwigms/picobrew_pico/issues/289 thanks to @sickchilly for the vector image work
> New iSpindle Image + Equipment Image Constraints

- app/main/routes_frontend.py
> strip recipe name on file creation

- app/main/routes_frontend.py
- app/static/js/pico_recipe.js
Sorting was missing from the list of still sessions #299. Adding a recipe step immediately after the last fixed step for the Pico S/C/Pro was difficult, requiring adding a step then moving it to the right place.
> Added sort to still session list

- app/main/routes_devices.py
- app/main/routes_frontend.py
- app/main/routes_pico_api.py
- app/main/routes_zseries_api.py
- app/main/session_parser.py
- app/static/css/main.css
- app/templates/devices.html
- app/templates/index.html
> visually indicate in the web UI metadata regarding session history and clean status

- app/main/routes_frontend.py
resolves https://github.com/chiefwigms/picobrew_pico/issues/318
> fix reference to tilt_sessions that was breaking the tilt history loading

- app/main/routes_frontend.py
- app/main/session_parser.py
- app/templates/_session_single.html
https://github.com/chiefwigms/picobrew_pico/issues/321
> Fix _session_single.html refactor for Download and Delete Session Actions

- app/static/js/brew_graph.js
- app/static/js/ferm_graph.js
- app/static/js/iSpindel_graph.js
- app/static/js/session_history.js
- app/static/js/still_graph.js
- app/static/js/tilt_graph.js
- app/templates/_session_list.html
- app/templates/_session_single.html
- app/templates/session_history.html
... typically you don't want to do this cause randomly accepting server HTML and arbitrarily evaling the <script> is dangerous ... whatever this is a closed system and who cares about security 🥷
> dynamically eval the <script> tags included in the paginated rendered HTML response

- app/main/routes_iSpindel_api.py
- app/main/routes_tilt_api.py
- app/main/session_parser.py
- app/static/js/ferm_graph.js
- app/static/js/ferm_graph_socketio.js
- app/static/js/iSpindel_graph.js
- app/static/js/iSpindel_graph_socketio.js
- app/static/js/tilt_graph_socketio.js
- create very basic standard ABV calculation and display realtime on the fermentation chart subtitle
- setup a reusable subtitle for use in hydrometer graphs (later I'll centralize both of these into a single implementation... maybe 🤷  since Tilt and iSpindel are essentially the same measurements of Temp and SG)
- port tilt graphing improvements from https://github.com/chiefwigms/picobrew_pico/pull/325 made by @wiltdavi into iSpindle/iSpindel graphs
cc/ @BuckoWA
> sync recent graphing improvements from tilt->ispindel and add ABV calculations

- app/main/session_parser.py
Thanks @BuckoWA ... yeah guess we aren't fermenting to 0.0468 % ABV 🤣
> ABV calc is in decimal, display should be in percentage

- app/main/config.py
- app/main/recipe_parser.py
- app/main/routes_frontend.py
- app/main/routes_pico_api.py
- app/main/routes_picoferm_api.py
- app/main/routes_picostill_api.py
- app/main/routes_zseries_api.py
- app/main/routes_zymatic_api.py
- app/static/js/base_recipe.js
- app/static/js/pico_recipe.js
- app/static/js/zseries_recipe.js
- app/static/js/zymatic_recipe.js
- app/templates/pico_recipes.html
- app/templates/recipe_actions.html
- app/templates/recipe_list.html
- app/templates/zseries_recipes.html
- app/templates/zymatic_recipes.html
Added a capability to "sync" similar to Picobrew Brew House. Supported it for all recipe types (pico, zymatic, and zseries). In doing so I tried to centralize some of the code related to recipe management and recipe editing, but didn't do everything as there is still some unique code between Pico (locked rows) and Zymatic/Zseries (which is more similar). Figured I did enough damage control already.
> Issue #195 - Sync/Archive Recipes (all recipe types)

- app/main/session_parser.py
**haven't tested with a zymatic physically**
I'm getting a Zymatic on Tuesday and will be able to run some tests with clean and rinse sessions to get the format right.
> include clean and rinse detection to zymatic device

- .github/dependabot.yml
- .github/workflows/docker-image.yml
- Dockerfile
- python 3.6 -> python 3.10
- nginx 1.15 -> nginx 1.22
- switch out python "full" for a slim version (manually installing other OS dependencies ourselves: git and gcc)
> Update Docker Build

- README.md
- docker-compose-no-ssl.yml
This set up is allowing me to run in Docker for my Cs
> Add docker-compose info that works for non-SSL installs
